# Generated by Django 6.0.6 on 2026-06-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
